/**
 * The API contract is defined once, server-side, and imported here as
 * type-only (erased at build time — nothing from src/ ends up in the bundle).
 */
export type {
  BookmarkEntry,
  BookmarksListResponse,
  BookmarksResponse,
  ChildSessionSummary,
  CompactionMark,
  ContextPoint,
  DiskSessionInfo,
  DiskUsageResponse,
  FileHistoryResponse,
  LiveResponse,
  LiveSession,
  FileSummary,
  HealthResponse,
  IndexedEvent,
  MaintenanceResponse,
  RelatedResponse,
  RelatedSession,
  MessageListResponse,
  MessageRow,
  PrefsResponse,
  ErrorSignaturesResponse,
  ProjectDetail,
  ProjectInfo,
  SavedSearch,
  SearchFacet,
  SearchFacets,
  SearchGroup,
  SearchHit,
  SearchResponse,
  SearchTimelineResponse,
  SessionContextResponse,
  SessionListResponse,
  SessionMeta,
  SessionMetaPatch,
  SearchAggregates,
  SessionChainResponse,
  SessionChildrenResponse,
  TimelineSession,
  SpendDay,
  SpendResponse,
  SpendSplit,
  StatsResponse,
  StatusResponse,
  TurnsResponse,
  TurnSummary,
} from '../../src/server/apiTypes';

export const SNIPPET_OPEN = '\uE000';
export const SNIPPET_CLOSE = '\uE001';
